crt/crt1.c: Fix merge error
Fix merge issue which resulted in non-CHERI compile error:
crt/crt1.c:25:8: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
   25 | hidden void_start_c(intptr_t *p)
      | ~~~~~~ ^
      | int

Fixes: 0720c199dbbb ("Merge remote-tracking branch 'vanilla/master' into cheri-musl-latest")
Signed-off-by: Stuart Menefy <stuart.menefy@codasip.com>