[Morello] musl-libc test sources: add (void) prototypes
In preparation for building with clang-15,
 https://git.morello-project.org/morello/llvm-project/-/merge_requests/293

Clang-15 has a new diagnostic:
src/regex.c:25:17: error: a function declaration without a prototype is
deprecated in all versions of C [-Werror,-Wstrict-prototypes]

100 test files have been updated to provide the missing prototypes.

The change is backward compatible with clang-14

Change-Id: I559a885b57a256f353c07e47625ffb4124227201